### ISSUE TITLE
failed creating a docker image from the http4k/amazonlinux-java-graal-ce-lambda-runtime:latest

### ISSUE THREAD

**Issue by kazurayam** [http4k/docker-images#4]
I am new to Http4k. I went through the online tutorial

- https://www.http4k.org/guide/tutorials/going_native_with_graal_on_aws_lambda/

I ran a "docker run" command as documented to create a zip which contains a GraalVM image. 

```
docker run -v $(pwd):/source \
    http4k/amazonlinux-java-graal-ce-lambda-runtime:latest \
    build/libs/HelloServerless-0.2.0-SNAPSHOT.jar \
    HelloServerlessGraal.zip
```

I got the following output in the console:

```
Creating native-image...
Warning: Ignoring server-mode native-image argument --no-server.
========================================================================================================================
GraalVM Native Image: Generating 'function' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                   (14.8s @ 0.22GB)
 Version info: 'GraalVM 22.3.1 Java 19 CE'
 Java version info: '19.0.2+7-jvmci-22.3-b12'
 C compiler: gcc (redhat, x86_64, 7.3.1)
 Garbage collector: Serial GC
[2/7] Performing analysis...  [**********]                                                             (124.8s @ 1.57GB)
   7,210 (87.27%) of  8,262 classes reachable
  10,268 (59.90%) of 17,142 fields reachable
  33,677 (53.52%) of 62,924 methods reachable
     348 classes,    95 fields, and 1,610 methods registered for reflection
      60 classes,    59 fields, and    55 methods registered for JNI access
       4 native libraries: dl, pthread, rt, z
[3/7] Building universe...                                                                              (13.2s @ 1.15GB)

Warning: Reflection method java.lang.Class.forName invoked at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:564)
Warning: Reflection method java.lang.Class.getMethods invoked at kotlin.internal.PlatformImplementations$ReflectThrowable.<clinit>(PlatformImplementations.kt:23)
Warning: Reflection method java.lang.Class.getDeclaredConstructor invoked at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:574)
Warning: Reflection method java.lang.Class.getDeclaredConstructor invoked at com.squareup.moshi.ClassFactory.get(ClassFactory.java:40)
Warning: Reflection method java.lang.Class.getDeclaredConstructor invoked at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:571)
Warning: Reflection method java.lang.Class.getDeclaredConstructor invoked at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:580)
Warning: Reflection method java.lang.Class.getDeclaredConstructor invoked at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:583)
Warning: Reflection method java.lang.Class.getField invoked at com.squareup.moshi.StandardJsonAdapters$EnumJsonAdapter.<init>(StandardJsonAdapters.java:278)
Warning: Reflection method java.lang.Class.getDeclaredFields invoked at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:136)
Warning: Aborting stand-alone image build due to reflection use without configuration.
com.oracle.svm.hosted.FallbackFeature$FallbackImageRequest: Reflection method java.lang.Class.forName invoked at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:564)
Reflection method java.lang.Class.getMethods invoked at kotlin.internal.PlatformImplementations$ReflectThrowable.<clinit>(PlatformImplementations.kt:23)
Reflection method java.lang.Class.getDeclaredConstructor invoked at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:574)
Reflection method java.lang.Class.getDeclaredConstructor invoked at com.squareup.moshi.ClassFactory.get(ClassFactory.java:40)
Reflection method java.lang.Class.getDeclaredConstructor invoked at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:571)
Reflection method java.lang.Class.getDeclaredConstructor invoked at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:580)
Reflection method java.lang.Class.getDeclaredConstructor invoked at com.squareup.moshi.internal.Util.generatedAdapter(Util.java:583)
Reflection method java.lang.Class.getField invoked at com.squareup.moshi.StandardJsonAdapters$EnumJsonAdapter.<init>(StandardJsonAdapters.java:278)
Reflection method java.lang.Class.getDeclaredFields invoked at com.squareup.moshi.ClassJsonAdapter$1.createFieldBindings(ClassJsonAdapter.java:136)
Aborting stand-alone image build due to reflection use without configuration.
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FallbackFeature.afterAnalysis(FallbackFeature.java:316)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$12(NativeImageGenerator.java:766)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:766)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
------------------------------------------------------------------------------------------------------------------------
                        5.7s (3.6% of total time) in 19 GCs | Peak RSS: 2.95GB | CPU load: 3.47
========================================================================================================================
Failed generating 'function' after 2m 33s.
Generating fallback image...
Warning: Image 'function' is a fallback image that requires a JDK for execution (use --no-fallback to suppress fallback image generation and to print more detailed information why a fallback image was necessary).
Building ZIP...
updating: bootstrap (stored 0%)
updating: function (deflated 68%)
Done!
```

Here I attach the zip file created by this process.

[HelloServerlessGraal.zip](https://github.com/http4k/docker-images/files/13910577/HelloServerlessGraal.zip)

I tried to deploy the resources on AWS using "pulumi up --stack dev --yes" as document. The deployed URL replied the following page:

```
<html>
<head><meta name="color-scheme" content="light dark"><style>:is([id*='google_ads_iframe'],[id*='taboola-'],.taboolaHeight,.taboola-placeholder,#credential_picker_container,#credentials-picker-container,#credential_picker_iframe,[id*='google-one-tap-iframe'],#google-one-tap-popup-container,.google-one-tap-modal-div,#amp_floatingAdDiv,#ez-content-blocker-container) {display:none!important;min-height:0!important;height:0!important;}</style><script src="chrome-extension://mooikfkahbdckldjjndioackbalphokd/assets/prompt.js"></script></head>
<body><pre style="word-wrap: break-word; white-space: pre-wrap;">{"message":"Internal Server Error"}</pre></body></html>
```

I looked at the AWS CloudWatch log where I found the following error message:

```
{
    "requestId": "RZ1oqh8UtjMEPYA=",
    "requestTime": "12/Jan/2024:01:57:49 +0000",
    "httpMethod": "GET",
    "httpPath": "/",
    "status": "500",
    "integrationError": "The Lambda function returned the following error: RequestId: 8d7b224c-9222-4236-8eb2-3e3ae3e3ca9c Error: Runtime exited with error: exit status 1. Check your Lambda function code and try again."
}
```

Clearly the deployed application is not working. How to fix this?

**Comment by daviddenton** [comment]
There were some problems (the tutorial was out of date) which I've fixed some of, but unfortunately it's still not working. The latest state is that it builds the image but still complains about the reflective access. This is strange because this definitely used to work. You can see where we've got to in this repo where I've worked through the tutorial stages and applied the latest version: https://github.com/http4k/helloworld

This is the latest error in the lambda logs - so the runtime is booting, but it looks like the reflective access has stopped it making a purely native image. 
```
INIT_START Runtime Version: provided:al2.v28	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:8bdc1e5642bbcd08528c3948a723b8901ec98ab986e6bab636fae24882de1d6c
--
Error: No bin/java and no environment variable JAVA_HOME
```

**Comment by daviddenton** [comment]
I've actually managed to fix the offending docker image so this should all work no with no more modifications (the tutorial was actually using an out-of-date image anyway which I've fixed the name of).

If you spot anything else wrong in the tutorial then please note it down and let us know. :)

**Comment by kazurayam** [comment]
Thank you for your prompt response.

> (the tutorial was actually using an out-of-date image anyway which I've fixed the name of).

The [turorial](https://www.http4k.org/guide/tutorials/going_native_with_graal_on_aws_lambda/) previously told us to use  the base docker image [`http4k/amazonlinux-java-graal-ce-lambda-runtime`](https://hub.docker.com/r/http4k/amazonlinux-java-graal-ce-lambda-runtime#!).

But now the tutorial tells us to use [`http4k/amazonlinux-java-graal-community-lambda-runtime`](https://hub.docker.com/r/http4k/amazonlinux-java-graal-community-lambda-runtime#!).

I tried the revised instruction, and got a success. Just great!
